### ISSUE TITLE
Is there any pre-trained model available?

### ISSUE THREAD

**Issue by quanhua92** [mkocabas/pose-residual-network#3]
Hi,
Your work is great. Look like your method can run at 23 frames / sec while having such good results. I want to ask if you have any plan to publish pre-trained models. 
Thank you very much.
Quan Hua

**Comment by salihkaragoz** [comment]
Hi,
Sorry for the late reply. We will not upload the whole code(Backbone and Subnets) due to some License problems. This is the PRN part of the paper. Also, We have uploaded the pre-trained model for Pytorch version. Keras version will be updated. I am closing this issue, please feel free for further questions.
Have a nice day
