### ISSUE TITLE
Will the rest of the MultiPoseNet framework be assembled ot this ?

### ISSUE THREAD

**Issue by dmenig** [mkocabas/pose-residual-network#4]
Hi. I'm very interested in this code, but unfortunately, it seems to only be usable if the actual major part of the undertaking is assembled, which is the backbone, the keypoint detector and the people detector described in the paper.

They seem to all come from different githubs. Will there be a streamlined integration to allow for easy testing and reproduction ?

Thanks.

**Comment by salihkaragoz** [comment]
Hi, 
First of all sorry for the late reply.

> Hi. I'm very interested in this code, but unfortunately, it seems to only be usable if the actual major part of the undertaking is assembled, which is the backbone, the keypoint detector and the people detector described in the paper.

We are planning to extend the repo to the way that accepting the different keypoint and Bbox results. Now it is working for only coco Ground truth results. 

> They seem to all come from different githubs. Will there be a streamlined integration to allow for easy testing and reproduction ?

We can't share the whole code(Backbone and Subnets) due to some license problems. BUT maybe we can share a tool to prepare results for PRN.

Please close this issue if you don't have any questions.
Thanks
